# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-05 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=6)),
                ('nick_name', models.CharField(blank=True, default='', max_length=32)),
                ('bio', models.CharField(blank=True, default='', max_length=3000)),
                ('mobile', models.CharField(blank=True, default='', max_length=16)),
                ('avator', models.ImageField(blank=True, null=True, upload_to='avator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_userprofile',
            },
        ),
    ]
