# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avator',
            field=models.ImageField(blank=True, default='/static/images/default_avator.jpg', upload_to='avator'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], default='m', max_length=6),
        ),
    ]
