# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171108_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avator',
            field=models.ImageField(blank=True, default='/avator/default_avator.jpg', upload_to='avator'),
        ),
    ]
