# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171115_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avator',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar/default_avatar.jpg', upload_to='avatar'),
        ),
    ]
