# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_oauthlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(0, '官方帐号'), (1, '微博'), (2, '微信'), (3, 'QQ')], default=0, verbose_name='用户类型'),
        ),
    ]
