# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthlogin',
            name='auth_type',
            field=models.IntegerField(choices=[(1, 'weibo'), (2, 'wechat'), (3, 'qq')], default=1, verbose_name='授权类别'),
        ),
    ]
