# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180308_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthlogin',
            name='auth_type',
            field=models.IntegerField(choices=[(1, 'weibo'), (2, 'wechat'), (3, 'qq'), (4, '支付宝')], default=1, verbose_name='授权类别'),
        ),
    ]
