# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='标题')),
                ('content_txt', models.TextField(default='', verbose_name='纯文本内容')),
                ('content_html', models.TextField(default='', verbose_name='html内容')),
                ('type', models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'Django'), (4, 'front end development')], default=1, verbose_name='类别')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='article/cover', verbose_name='封面图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('release_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('is_released', models.BooleanField(default=False, verbose_name='是否发布')),
                ('page_views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('content', models.CharField(default='', max_length=140, verbose_name='评论内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='博文')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Comment', verbose_name='上级评论')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
