# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171115_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='replier',
        ),
        migrations.RemoveField(
            model_name='praise',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='author_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='博文'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentator_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='comment_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='所属评论'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='receiver_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='接受者'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='replier_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='回复人'),
        ),
        migrations.AddField(
            model_name='praise',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='点赞人'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='parent_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='点赞对象id'),
        ),
    ]
