# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20171204_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'Django'), (4, '前端技术'), (5, '随笔'), (6, '历史'), (7, '数码资讯'), (8, '读书'), (9, '问答')], default=1, verbose_name='类别'),
        ),
    ]
