# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20171205_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praise',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='点赞对象id'),
        ),
        migrations.AlterIndexTogether(
            name='praise',
            index_together=set([('praise_type', 'parent_id')]),
        ),
    ]
