# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180108_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_viewed',
            field=models.BooleanField(default=0, verbose_name='是否已查看'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='is_viewed',
            field=models.BooleanField(default=0, verbose_name='是否已查看'),
        ),
        migrations.AddField(
            model_name='praise',
            name='is_viewed',
            field=models.BooleanField(default=0, verbose_name='是否已查看'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'Django'), (4, '前端技术'), (5, '随笔'), (6, '历史'), (7, '数码资讯'), (8, '读书'), (9, '问答'), (10, '话题')], default=1, verbose_name='类别'),
        ),
    ]
