# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180110_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间'),
        ),
    ]
