# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180112_1459'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='article',
            index_together=set([('is_released', 'author_id', 'type'), ('is_released', 'type')]),
        ),
    ]
