# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180417_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
    ]
