# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20180624_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.AlterField(
            model_name='praise',
            name='praise_type',
            field=models.IntegerField(choices=[(1, '博文'), (2, '评论')], default=1, verbose_name='点赞类型'),
        ),
    ]
